name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_SECRET }}
          user: pubudu91
          base_indepth: yes
          base_hireable: yes
          repositories: 300
          commits_authoring: pubudu91, pubudu.fernando@gmail.com, pubuduf@wso2.com, pubudu.12@cse.mrt.ac.lk
          repositories_forks: yes
          repositories_affiliations: ""
        
  interesting-facts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_SECRET }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: USA/EST

  indepth-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_SECRET }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 20
          plugin_languages_analysis_timeout: 15

  full-history-calendar:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_SECRET }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 7

  achievements:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_SECRET }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0  

  notable-contributions:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.notable.indepth.svg
          token: ${{ secrets.METRICS_SECRET }}
          base: ""
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_types: commit, pull_request

